language: node_js
node_js:
  - "node"
os: linux
dist: focal
group: edge
branches:
  only:
    - source
git:
  depth: 3
  submodules: false
  quiet: true
cache:
  apt: true
  directories:
    - node_modules
before_install:
  - npm install -g hexo highlight.js@9.14.2
  - git submodule update --init
  - git submodule update --remote --recursive
install:
  - npm install
before_script:
  - git config --global user.name rokibhasansagar
  - git config --global user.email rokibhasansagar2014@outlook.com
  - sed -i "s/__GitOAuthToken__/${GitOAUTHToken}/" _config.yml
script:
  - hexo clean && hexo generate
after_success:
  - hexo deploy --silent
