name: Node.js CI

on:
  push:
    branches: [ source ]
  pull_request:
    branches: [ source ]

jobs:
  build:

    runs-on: [ubuntu-latest, ubuntu-20.04]

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g hexo highlight.js@9.14.2
    - run: git submodule update --init
    - run: git submodule update --remote --recursive
    - run: npm install
    - run: hexo clean && hexo generate
